"""公共基础：常量、错误码、统一异常、ID 生成、时间工具。"""

from common.constants import APP_NAME, APP_VERSION, AgentName
from common.error_codes import ErrorCode
from common.exceptions import (
    A2AAgentNotFoundError,
    A2AError,
    A2AMessageInvalidError,
    A2ANetworkError,
    A2AProtocolVersionMismatchError,
    A2ATaskNotFoundError,
    A2ATimeoutError,
    AgentError,
    AgentParseError,
    AppException,
    AuthenticationError,
    AuthorizationError,
    ConfigError,
    EventPublishError,
    EventSubscribeError,
    LLMAllProvidersFailedError,
    LLMError,
    LLMNotConfiguredError,
    LLMRateLimitError,
    LLMResponseInvalidError,
    LLMTimeoutError,
    MCPError,
    MCPPromptNotFoundError,
    MCPProtocolVersionMismatchError,
    MCPResourceNotFoundError,
    MCPToolExecutionError,
    MCPToolNotFoundError,
    NotFoundError,
    RegulationVersionMissingError,
    ServiceUnavailableError,
    StorageError,
    StorageReadError,
    TaskError,
    TaskStateConflictError,
    ValidationError,
)
from common.ids import (
    alert_id,
    case_id,
    event_id,
    inspection_id,
    message_id,
    new_id,
    new_ulid,
    plan_id,
    project_id,
    regulation_id,
    report_id,
    standard_id,
    task_id,
    tenant_id,
    violation_id,
)
from common.timeutils import ensure_utc, from_iso, to_iso, utc_now

__all__ = [
    # 常量
    "APP_NAME",
    "APP_VERSION",
    "AgentName",
    "ErrorCode",
    # 异常
    "AppException",
    "ConfigError",
    "ValidationError",
    "NotFoundError",
    "ServiceUnavailableError",
    "AuthenticationError",
    "AuthorizationError",
    "LLMError",
    "LLMNotConfiguredError",
    "LLMTimeoutError",
    "LLMRateLimitError",
    "LLMResponseInvalidError",
    "LLMAllProvidersFailedError",
    "A2AError",
    "A2AMessageInvalidError",
    "A2AAgentNotFoundError",
    "A2AProtocolVersionMismatchError",
    "A2ATaskNotFoundError",
    "A2ATimeoutError",
    "A2ANetworkError",
    "MCPError",
    "MCPResourceNotFoundError",
    "MCPToolNotFoundError",
    "MCPToolExecutionError",
    "MCPProtocolVersionMismatchError",
    "MCPPromptNotFoundError",
    "EventPublishError",
    "EventSubscribeError",
    "AgentError",
    "AgentParseError",
    "RegulationVersionMissingError",
    "TaskError",
    "TaskStateConflictError",
    "StorageError",
    "StorageReadError",
    # ID 工厂
    "new_ulid",
    "new_id",
    "tenant_id",
    "project_id",
    "plan_id",
    "inspection_id",
    "violation_id",
    "alert_id",
    "report_id",
    "task_id",
    "regulation_id",
    "standard_id",
    "case_id",
    "event_id",
    "message_id",
    # 时间
    "utc_now",
    "ensure_utc",
    "to_iso",
    "from_iso",
]
